### ISSUE TITLE
Rename the derived project

### ISSUE THREAD

**Issue by lolmaus** [douglasduteil/fake-breakpoint-slicer#1]
Hi.

Author of original Breakpoint Slicer here. Found your fork tonight by accident.

For you to know, Breakpoint Slicer is growing in features. Support for named slices has been [introduced](https://github.com/lolmaus/breakpoint-slicer#calling-slices-by-names-rather-than-numbers) in v1.3, without abandoning support for Sass 3.2. Also, a major update is being planned. It's gonna leverage maps, allow for compound media queries, stop depending on Compass etc. Vertical media queries might also be included (join the discussion [here](https://github.com/lolmaus/breakpoint-slicer/issues/9)).

If you're going to maintain the derived project, i kindly request that you rename it to prevent any confusion and collisions.

Also, please release the `breakpoint-slicer` name in the Bower registry.

**Comment by lolmaus** [comment]
Technically, it's not even a fork. I see you started with a different codebase, while, ughm... borrowing the original idea, name and readme.

**Comment by douglasduteil** [comment]
Wow sorry dude. It's true I copy/paste you're stuff for a private use... Hope you're not supa mad...
But my stuff is not on Bower http://bower.io/search/?q=breakpoint-slicer

BTW I learned a lot reading your code. Thanks

**Comment by lolmaus** [comment]
Was cleaning up my inbox and discovered that i hadn't replied to you.

Thank you for renaming the project!

Don't forget to share your thoughts and ideas for Breakpoint Slicer's future version [here](https://github.com/lolmaus/breakpoint-slicer/issues/9).
